### ISSUE TITLE
Couldnt Import 

### ISSUE THREAD

**Issue by arslanaybars** [feroseali/cafebeside#1]
I clone your repo, but i couldnt run in my computer ?

is this android studio project or eclipse, i am using android studio mayeb thats why i couldnt

do you have any idea how can i run this project?

**Comment by feroseali** [comment]
i used eclipse.Yes,you can migrate it to android studio.Its not completely done,It's an ongoing project.

**Comment by arslanaybars** [comment]
okey i will try again thank you. Have good work :+1:

**Comment by aroh4444** [comment]
Hello, when i start the project, i cannot connect to the network.

Please can you help me how to do so ?

**Comment by feroseali** [comment]
Hey aroh4444, i developed this for some students,as their final year projct.
Its developed in assumption that it belongs to a local wifi network,provided by the restaurant.
I check the ssid of the wifi connection,whether it matches or not.
Now i declared it as "Area-51". Change your ssid into "Area-51", You can access it.

**Comment by aroh4444** [comment]
Hello, I cannot change my ssid, where can i modify it on the codes please ?

**Comment by feroseali** [comment]
Hey,
There is a Configuration.java file, There you can change it.
cafebeside/src/com/team/cafebeside/configs/Configuration.java

**Comment by aroh4444** [comment]
Hello back, yeah i did changed it exactly how my ssid of my network is, it still tells me that i cannot connect sadly.

Your project looks good but i cannot run it /= 
Thanks for you response feroseali

**Comment by aroh4444** [comment]
Hey it is good now, thanks bro for your help (y)

**Comment by aroh4444** [comment]
Hello,

I cannot find the database and where are the PHP files located, please bro /=

**Comment by feroseali** [comment]
Sorry,I didn't added that yet.I will add it soon.
